development:
  :address: mail.csg.org
  :port: 25
  :authentication: login
  :user_name: emap@csg.org
  :password: Emap8222
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: esraemap
  :password: EMAP8train
  :enable_starttls_auto: true
